### PR TITLE
di for example providers

### LINKED ISSUE #2: DI
Not sure if that is an issue but will be nice if examples will be using built in DI

In our case we wish to be able to inject repo into example constructor and provide record right from db instead of hardcoding it

e.g. will be nice if there will be ability to write something like (pseudo code):

```
class ManagerExample implements Example {
    private readonly Repo _repo;
   ctor(repo);
   getExample => repo.findById(1);
}
```

### PR DESCRIPTION
**Pull request by mac2000**
This will fix #2 

It is backward compatible so if user wont need it nothing will change, but if you are gonna need di for your example providers you may use it

sorry but seems that my vs reformatted code with tabs instead of spaces if that is an issue just let me know

### CODE REVIEW

**Comment by mattfrear** [comment]
Hi @mac2000 

Thank you for your pull request. I am sorry for the delay, I only just noticed this yesterday as I wasn't receiving notifications from GitHub of issues or PRs.

Could you fix the formatting issues please, i.e. spaces instead of tabs, and merge the conflicts?

**Comment by mac2000** [comment]
@mattfrear  oh, something strange is going on, I also did not received any notifications, I did pull changes and resolve conflicts, also converted tabs to spaces (sorry for that, will be nice to have editorconfig in repo so VS will automatically switch settings). Hope now everything is OK

**Comment by mattfrear** [comment]
Looks good, thanks mac2000!

PS. I wasn't receiving notifications because I wasn't "Watching" this repo. I thought as the repo owner I would automatically be watching it, but nope.

**Comment by mac2000** [comment]
Thank you, will also turn on watching now to wait for new version released

**Pull request merged**
